"""Model-free incident brief rendering from typed source-backed data."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from html import escape

from disaster_monitor.application.incidents.models import (
    ActiveIncident,
    DisasterIncidentCoverage,
)


@dataclass(frozen=True, slots=True)
class DeterministicIncidentBrief:
    title: str
    html: str
    generated_by: str
    generated_at: datetime


class DeterministicIncidentBriefBuilder:
    version = "deterministic-incident-brief:v1"

    def build(
        self,
        incident: ActiveIncident,
        *,
        coverage: DisasterIncidentCoverage,
        retrieved_at: datetime,
        gaps: tuple[str, ...] = (),
    ) -> DeterministicIncidentBrief:
        title = (
            f"{incident.disaster.value.replace('_', ' ').title()} — {incident.location}"
        )
        measurements = (
            "".join(
                "<li>"
                + escape(item.kind.value.replace("_", " ").title())
                + ": "
                + escape(str(item.value))
                + (" " + escape(item.unit) if item.unit else "")
                + "</li>"
                for item in incident.measurements
            )
            or "<li>No source-backed measurements were supplied.</li>"
        )
        gap_items = "".join(f"<li>{escape(item)}</li>" for item in gaps) or (
            "<li>No additional gap was recorded for this brief.</li>"
        )
        html = (
            '<!doctype html><html lang="en"><head><meta charset="utf-8">'
            f"<title>{escape(title)}</title>"
            "<style>body{font:16px system-ui;max-width:860px;margin:2rem auto;"
            "line-height:1.5}dt{font-weight:700}footer{margin-top:2rem;color:#555}"
            "@media print{body{margin:0.5in}}</style></head><body>"
            f"<h1>{escape(title)}</h1><dl>"
            f"<dt>Occurrence</dt><dd>{escape(_utc(incident.event_time))}</dd>"
            f"<dt>Activity</dt><dd>{escape(incident.activity_status.value)}</dd>"
            f"<dt>Coverage</dt><dd>{escape(coverage.state.value)} — "
            f"{escape(coverage.detail)}</dd></dl>"
            f"<h2>Source-backed measurements</h2><ul>{measurements}</ul>"
            f"<h2>Known gaps</h2><ul>{gap_items}</ul>"
            "<h2>Provenance</h2>"
            f'<p><a href="{escape(incident.source.canonical_url, quote=True)}">'
            f"{escape(incident.source.publisher)} — "
            f"{escape(incident.source.title)}</a></p>"
            f"<footer>Retrieved {escape(_utc(retrieved_at))}. Generated by "
            f"{self.version}; no language model was used.</footer></body></html>"
        )
        return DeterministicIncidentBrief(title, html, self.version, retrieved_at)


def _utc(value: datetime) -> str:
    return value.astimezone(UTC).isoformat().replace("+00:00", "Z")


__all__ = ["DeterministicIncidentBrief", "DeterministicIncidentBriefBuilder"]
